INSERT INTO Miage.dbo.ADMINISTRATEUR
(NOM, PRENOM, NUM_TELEPHONE, EMAIL, SURNOM, PASSWORD)
VALUES('Halim', 'Lakfifi', '+212 0684160456', 'alakfifi900@gmail.com', 'admin', 'admin');

INSERT INTO Miage.dbo.PROF
(ID_ADMIN, NOM, PRENOM, NUM_TELEPHONE, SALAIRE, CIN, SURNOM, PASSWORD)
VALUES(1, 'taibi', 'zouhir', '0699999999', 90000, 'AB00000', 'prof', 'prof');

INSERT INTO Miage.dbo.FILIER
(NOM, SPECIALITE)
VALUES('developpement Informatique', 'INFORMATIQUE');

INSERT INTO Miage.dbo.ETUDIANT
(ID_ADMIN, ID_FILIER, NOM, PRENOM, ADRESSE, TELEPHONE, AUTRE_PHONE, PHOTOS, SURNOM, MOTS_DE_PASSE)
VALUES(1, 1, 'halim', 'lakfifi', 'Hay essalam rue lajoaud n 446', '0684160456', '06 00 00 00 00', 'PATH', 'etudiant', 'etudiant');


INSERT INTO Miage.dbo.ABSENCE
(ID_ETUDIANT, [DATE])
VALUES(1, '12/06/2021');

INSERT INTO Miage.dbo.FACTURE
(ID_ETUDIANT, ID_ADMIN, MONTANT, MOISPAYE, [DATE])
VALUES(1, 1, 800, 'Juin', '06/12/2021');

INSERT INTO Miage.dbo.MODULE
(MODULE, COEFFICIENT)
VALUES('programmation structurer', 7);

INSERT INTO Miage.dbo.NOTES
(ID_MODULE, ID_PROF, ID_ETUDIANT, LA_NOTE, REMARQUE)
VALUES(1, 1, 1, 20, 'parfait');

INSERT INTO Miage.dbo.SALLE
(NOM_SALLE, [TYPE])
VALUES('SALLE COUR 2', 'SC');


INSERT INTO Miage.dbo.EMPLACEMENT
(ID_SALLE, ID_MODULE)
VALUES(1, 1);

INSERT INTO Miage.dbo.ENSEIGNEMENT
(ID_PROF, ID_MODULE)
VALUES(1, 1);

INSERT INTO Miage.dbo.INTEGRATION
(ID_FILIER, ID_MODULE)
VALUES(1, 1);

